### ISSUE TITLE
Need LICENSE

### ISSUE THREAD

**Issue by rgaiacs** [MathML/logo#1]
Can we add `LICENSE`? I would like CC-BY.

**Comment by fred-wang** [comment]
This is discussed on the "MathML Logo follow-up" thread.

**Comment by fred-wang** [comment]
I've clarify the licenses used: https://github.com/MathML/logo/#licenses

Now it remains to decide the license for the logo files itself:
https://mathml.github.io/logo/manifest.txt

**Comment by rgaiacs** [comment]
Thanks @fred-wang for the commits.

**Comment by fred-wang** [comment]
I'm closing this issue since the remaining work is now handled in https://github.com/MathML/logo/pull/4
