### ISSUE TITLE
Need to change the size of page of mathml-logo.svg

### ISSUE THREAD

**Issue by rgaiacs** [MathML/logo#3]
The page of `mathml-logo.svg` doesn't comport our logo. We only got "Associatio" instead of "Association".

**Comment by fred-wang** [comment]
The Latin Modern Math and TeX Gyre Heros font must be used to get the right size.

**Comment by rgaiacs** [comment]
> The Latin Modern Math and TeX Gyre Heros font must be used to get the right size.

Thanks.

**Comment by fred-wang** [comment]
I suggest using the *-text-as-path versions on our website to avoid this kind of issue with Local/Web fonts and speed up the initial logo downloading:

https://mathml.github.io/logo/
![logo-download](https://cloud.githubusercontent.com/assets/567455/9154481/f1df6d5c-3e8f-11e5-9a0d-a2b6e4c1c3e0.png)
